version: '3.8'

services:
  sling-syncer:
    build: .
    container_name: sling-syncer
    restart: unless-stopped
    environment:
      - SLING_TOKEN=${SLING_TOKEN}
      - ORG_ID=${ORG_ID}
      - USER_ID=${USER_ID}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      - REDIRECT_URI=${REDIRECT_URI}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    ports:
      - "5369:5369"
    volumes:
      - .:/usr/src/app